server:
  port: 7002
  
spring:
  application:
    name: jeecg-demo
  cloud:
    nacos:
      config:
        server-addr: jeecg-boot-nacos:8848
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
  config:
    import:
      - optional:nacos:jeecg.yaml
      - optional:nacos:jeecg-@profile.name@.yaml